name: Compile and test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get update -y ; sudo apt-get install --yes build-essential ; sudo apt-get install --yes cmake ; sudo apt-get install --yes gcc ; sudo apt-get install --yes g++
    - name: create directories
      run: mkdir -p $HOME/.local/include ; mkdir -p $HOME/.local/lib ; mkdir -p $HOME/.local/bin ; sudo mkdir -p /root/.local/lib ; sudo mkdir -p /root/.local/include ; sudo mkdir -p /root/.local/bin
    - name: make
      run: make ; make instal ; sudo make install ; cp ./libscss.a tests/. ; sudo mkdir -p /usr/local/include/scss ; sudo cp -r src/include/* /usr/local/include/scss/.
    - name: tests
      run: cd tests && make && ./test.out
